---
abstract: 'be more like RJBS -- use the modules he likes!'
author:
  - 'Ricardo Signes <rjbs@cpan.org>'
build_requires:
  Test::More: 0.96
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-RJBS
requires:
  App::Ack: 1.82
  App::Cmd: 0.308
  App::Nopaste: 0.34
  App::Uni: 0
  App::Whiff: 0
  App::cpanminus: 1.1002
  App::cpanoutdated: 0.12
  App::grindperl: 0
  CPAN::Mini: 0.563
  Carp::Always: 0
  Config::GitLike: 0
  Config::INI: 0.011
  Crypt::SSLeay: 0
  DBD::SQLite: 0
  Data::GUID: 0.044
  DateTime: 0.51
  Devel::Cover: 0
  Devel::NYTProf: 0
  Dist::Zilla: 5
  Dist::Zilla::PluginBundle::RJBS: 1.012
  Email::Filter: 1.02
  Email::MIME: 1.905
  Email::Sender: 0
  Email::Sender::Transport::SQLite: 0
  File::Rename: 0
  HTML::Element: 3.22
  IO::Socket::SSL: 0
  JSON: 2.12
  LWP::Protocol::https: 0
  List::AllUtils: 0
  Log::Dispatchouli: 2.000
  Module::CoreList: 2.68
  Module::Which: 0
  Moose: 1.19
  MooseX::StrictConstructor: 0
  Mozilla::CA: 0
  PPI: 1.212
  Params::Util: 0.38
  Perl::Tidy: 20071205
  Plack: 0
  Pod::Cpandoc: 0
  Pod::Weaver: 4
  Scalar::Util: 1.18
  Sub::Exporter: 0.980
  Term::ReadLine::Gnu: 1
  Text::Markdown: v1.0.24
  Throwable: 0.102080
  Throwable::X: 0
  Try::Tiny: 0.007
  Unicode::Tussle: 0
  namespace::autoclean: 0
  perl: v5.14.0
  warnings: 0
resources:
  bugtracker: https://github.com/rjbs/Task-BeLike-RJBS/issues
  homepage: https://github.com/rjbs/Task-BeLike-RJBS
  repository: https://github.com/rjbs/Task-BeLike-RJBS.git
version: 20131116.000
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Filter/Git::GatherDir'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@Filter/CheckPrereqsIndexed'
      version: 0.009
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@Filter/CheckExtraTests'
      version: 0.016
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@Filter/RJBS-Outdated'
      version: 0.013
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      name: '@Filter/CPAN-Outdated'
      version: 0.013
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Filter/PruneCruft'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Filter/ManifestSkip'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Filter/MetaYAML'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Filter/License'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Filter/Readme'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Filter/ExecDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Filter/ShareDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Filter/MakeMaker'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Filter/Manifest'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Filter/TestRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Filter/ConfirmRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Filter/UploadToCPAN'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@Filter/AutoVersion'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Test::ChangesHasContent
      name: '@Filter/Test::ChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.10
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@Filter/TestMoreWithSubtests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@Filter/TaskWeaver'
      version: 0.101626
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Filter/GithubMeta'
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 2.017
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.006
