---
abstract: 'be more like RJBS -- use the modules he likes!'
author:
  - 'This is free software, released under the'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-RJBS
no_index:
  directory:
    - inc
    - t
requires:
  App::Ack: 1.76
  App::Addex: 0.013
  App::Addex::AddressBook::Apple: 0.006
  App::Cmd: 0.010
  App::Smarkmail: 0
  App::Whiff: 0
  CPAN: 1.87
  CPAN::Mini: 0.563
  CPAN::Reporter: 0
  Config::INI: 0.011
  DBD::SQLite: 0
  Data::GUID: 0.043
  DateTime: 0.41
  Email::Filter: 1.02
  Email::MIME: 1.861
  Exception::Class: 1.23
  HTML::Element: 3.22
  List::MoreUtils: 0.21
  Log::Dispatchouli: 0
  Mac::Glue: 1.30
  Mixin::ExtraFields: 0.005
  Mixin::ExtraFields::Param: 0.011
  Module::CoreList: 2.13
  Module::Install: 0.68
  Moose: 0.35
  MooseX::POE: 0.07
  MooseX::Singleton: 0.05
  POE::Component::IRC: 0
  PPI: 1.201
  Params::Util: 0.23
  Perl::Critic: 1.080
  Perl::Critic::Lax: 0.007
  Scalar::Util: 1.18
  Sub::Exporter: 0.978
  Text::Markdown: 1.0.2
  YAML::XS: 0
  perl: 5.8.0
  pip: 0.12
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/task-belike-rjbs
version: 1.003
